FROM node:18 AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
# docker-compose-prod에 명시된 args(변수)를 이미지 빌드시 환경 변수로 사용한다.
ARG REACT_APP_NAME
ENV REACT_APP_NAME="PROD_REACT_SERVICE"
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html